baseurl = "https://mpas.github.io"

# website title
title = "Marco Pas"

# theme name
theme = "flyweight"

# default amount of posts in each pages
paginate = 12

# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = "UA-180712180-1"

# whether to use robots.txt
enableRobotsTXT = true

# whether to use emoji code
enableEmoji = true

[outputs]
    home = ["HTML", "RSS", "Lunr"]

[outputFormats.Lunr]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[Permalinks]
    posts = "/posts/:year/:month/:day/:filename/"
    pages = "/pages/:filename/"

[Params]
    # the date format to use
    dateFormat = "January 2, 2006"

    # language code ["en", "zh-CN", "fr", "pl", ...]
    languagecode = "en-US"

    # name of the site author; used in header meta information
    author = "Marco Pas"

    # social links; used in footer, these must be full URLs!
    twitter = "https://twitter.com/marcopas"
    github = "https://github.com/mpas"
    stackoverflow = "http://stackoverflow.com/users/185432/marco"
    linkedin = "https://www.linkedin.com/in/marcopas"
    email =  "mailto:marco.pasopas@gmail.com"

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
        icon = "fas fa-book has-text-primary"

[[menu.main]]
    name = "Archive"
    url = "/posts"
    weight = 2
    [menu.main.params]
        icon = "fas fa-archive has-text-warning"

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
    [menu.main.params]
        icon = "fas fa-tag has-text-danger"

[[menu.main]]
    name = "About"
    url = "/pages/about/"
    weight = 4
    [menu.main.params]
        icon = "fas fa-address-card has-text-success"
